#!/bin/bash

# NOTE: Requires ffmpeg
if command -v ffmpeg >/dev/null 2>&1; then
    # Make CAF versions of WAV files
    ffmpeg -loglevel error -y -i "Art/Sonar Song.wav" Resources/s_break.caf
    ffmpeg -loglevel error -y -i "Art/Sonar Descent.wav" Resources/s_next.caf
    ffmpeg -loglevel error -y -i "Art/Fancy Toast.wav" Resources/s_rebalance.caf
    ffmpeg -loglevel error -y -i "Art/Double Sonar Ping.wav" Resources/s_start.caf
    ffmpeg -loglevel error -y -i "Art/Sonar Ping.wav" Resources/s_warning.caf
else
    echo "Error: ffmpeg not found - cannot build CAF files" >&2
    cp "$1" "$2" "$3"
fi

# Call make-icns to make icns files for macOS native build
tools/make-icns "Art/piranha_bare.pdf" "Resources/tbfile.icns"